name: build
on: push

jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}   
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [12, 14]

    steps:
      - name: my first step
        env:
          MY_VAR: HI there! my name is
          FIRST_NAME: Al
          MIDDLE: G
          LAST: RIB
        run: echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
